# Generated by Django 4.1.1 on 2022-09-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promo", "0002_promoimage_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promo",
            name="link",
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="promo",
            name="name",
            field=models.CharField(default="Product", max_length=500),
            preserve_default=False,
        ),
    ]
