# Generated by Django 4.1.1 on 2022-09-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promo", "0003_alter_promo_link_alter_promo_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promo",
            name="name",
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
