# Generated by Django 4.1.1 on 2022-09-22 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("promo", "0004_alter_promo_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promoimage",
            name="promo",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="promo.promo",
            ),
        ),
    ]
